spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/was
    username: "postgres"
    password: "se7540"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 1000
        default_schema:
  data:
    redis:
      port: 6379
      host: redis
      password:
server:
  port: 8080
  address: 0.0.0.0
